# Generated by Django 5.0.6 on 2024-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooksubtopic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebooktopic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
