# Generated by Django 5.0.6 on 2024-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_management', '0004_alter_notebook_user_alter_notebooksubtopic_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooksubtopic',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notebooktopic',
            name='order',
            field=models.IntegerField(),
        ),
    ]
