# Generated by Django 5.0.6 on 2024-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_management', '0005_alter_notebooksubtopic_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='room_id',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
