# Generated by Django 5.0.6 on 2024-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_management', '0006_notebook_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='permission_type',
            field=models.CharField(default='owner', max_length=10),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='room_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
