# Generated by Django 5.0.6 on 2024-08-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_management', '0008_remove_notebook_permission_type_sharednotebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednotebook',
            name='permission_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('write', 'Write')], max_length=10),
        ),
    ]
